config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :articles
  #root 'pages#home'
  root 'articles#index'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ edit update destroy ]

  def edit
  end

  def create
    @comment = current_user.comment.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@comment.article_id), notice: "Comment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@comment.article_id), notice: "Comment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to article_path(@comment.article_id), notice: "Comment was successfully destroyed." }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:text, :article_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="border rounded p-4 mb-4">
  <div class="mb-2">
    <p class="font-semibold text-gray-800"><%= comment.user.full_name %></p>
    <p class="text-gray-600"><%= comment.created_at.strftime("%B %e, %Y %l:%M%P") %></p>
  </div>

  <p class="mb-4 text-gray-700"><%= comment.text %></p>

  <% if current_user == comment.user %>
  <div class="flex items-center">
    <%= button_to 'Delete comment', comment_path(comment), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class: "text-red-500 hover:underline" %>
  </div>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: "mt-6") do |form| %>
  <div class="mb-4">
    <%= form.hidden_field :article_id, value: article.id %>
  </div>

  <div class="mb-4">
    <%= form.label :text, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :text, class: "w-full px-3 py-2 leading-tight border border-gray-300 rounded shadow-sm focus:outline-none focus:shadow-outline-blue focus:border-blue-500" %>
  </div>

  <div class="mb-6">
    <%= form.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>